# local development backend
local_backend: true

# github backend
backend:
  name: github
  repo: teknologi-pendidikan/universe
  branch: main

site_url: https://lofi.teknologipendidikan.or.id
logo_url: https://lofi.teknologipendidikan.or.id/logo-lofi.svg
locale: id
search: false

media_folder: 'apps/oer-center/public/content'
public_folder: '/content'
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  # TEAM REDAKSI COLLECTION
  - name: 'oercontent'
    label: 'OER Hub Content'
    editor:
      preview: false
    delete: false
    files:
      - label: 'Learning Content'
        name: 'contentdata'
        file: 'apps/oer-center/data/learning.content.json'
        fields:
          - label: 'Content List'
            name: 'learningcontent'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Title', name: 'contentTitle', widget: 'string' }
              - { label: 'UUID', name: 'uuid', widget: 'string' }
              - { label: 'Author', name: 'contentAuthor', widget: 'string' }
              - {
                  label: 'Content Type',
                  name: 'contentType',
                  widget: 'select',
                  options: ['video', 'image', 'slides', 'text'],
                }
              - { label: 'Description', name: 'contentDescription', widget: 'text' }
              - { label: 'Thumbnail', name: 'contentThumbnail', widget: 'string' }
              - { label: 'Content URL', name: 'contentUrl', widget: 'string' }
              - { label: 'Upload Date', name: 'contentUploadDate', widget: 'string' }

  - name: 'thematicontent'
    label: 'Thematic Content'
    editor:
      preview: false
    delete: false
    files:
      - label: 'Thematic Content'
        name: 'thematicdata'
        file: 'apps/oer-center/data/thematic.content.json'
        fields:
          - label: 'Thematic List'
            name: 'thematiclist'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Title', name: 'thematicTitle', widget: 'string' }
              - { label: 'UUID', name: 'uuid', widget: 'string' }
              - { label: 'Description', name: 'thematicDescription', widget: 'text' }
              - { label: 'Thumbnail', name: 'thematicThumbnail', widget: 'string' }
              - label: 'Learning Content List'
                name: 'thematicLearningContents'
                widget: 'relation'
                collection: 'oercontent'
                search_fields: ['learningcontent.*.contentTitle', 'learningcontent.*.contentDescription']
                value_field: 'learningcontent.*.uuid'
                display_fields: ['learningcontent.*.contentTitle']
                multiple: true
