# local development backend
local_backend: true

# github backend
backend:
  name: github
  repo: teknologi-pendidikan/universe
  branch: main

site_url: https://lofi.teknologipendidikan.or.id
logo_url: https://lofi.teknologipendidikan.or.id/logo-lofi.svg
locale: id
search: false

media_folder: 'apps/lofi/public/posts'
public_folder: '/posts'
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  # ARTIKEL COLLECTION
  - name: 'posts'
    label: 'Artikel Berita'
    folder: 'apps/lofi/_post'
    create: true
    format: 'frontmatter'
    sortable_fields:
      - 'title'
      - 'date'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'string' }
      - { label: 'description', name: 'description', widget: 'text' }
      - { label: 'category', name: 'category', widget: 'string' }
      - label: 'Repoter'
        name: 'author'
        widget: 'relation'
        collection: 'redaksi'
        search_fields: ['reporterlist.*.username', 'reporterlist.*.name']
        value_field: 'reporterlist.*.username'
        display_fields: ['reporterlist.*.name']
      - { image: 'image', label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    view_filters:
      - label: 'Artikel Opini'
        field: 'category'
        pattern: 'opini'
      - label: 'Artikel Refensi'
        field: 'category'
        pattern: 'referensi'

  # TEAM REDAKSI COLLECTION
  - name: 'redaksi'
    label: 'Tim Redaksi'
    editor:
      preview: false
    delete: false
    files:
      - label: 'Reporter Berita'
        name: 'reporter'
        file: 'apps/lofi/data/redaksi.json'
        fields:
          - label: 'Reporter Berita'
            name: 'reporterlist'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'username', name: 'username', widget: 'string' }
              - { label: 'Role', name: 'role', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
